Repository filetrust/icap-management-ui-tests, pull requests merged in 2020-10, with the labels that each got.

#46 added remaining steps for user-records-admin.steps.js
  specs/step_definitions/user-records-admin.steps.js
  src/pages/users.page.js
Labels: Feature-627

#53 added steps for request-history-log.feature
  specs/features/request-history-log.feature
  specs/step_definitions/request-history-log.steps.js
  src/pages/request-history.page.js
Labels: Changes requested, Feature-627

#55 Steps for dashboard-requests-metrics-display & dashboard-requests-filtering-by-process-date.feature
  specs/features/dashboard-requests-filtering-by-process-date.feature
  specs/features/dashboard-requests-metrics-display.feature
  specs/features/user-records-admin.feature
  specs/features/user-session-admin.feature
  specs/step_definitions/dashboard-metrics-for-processed-files.steps.js
  specs/step_definitions/dashboard-requests-filtering-by-process-date.steps.js
  specs/step_definitions/dashboard-requests-metrics-display.steps.js
  specs/step_definitions/user-records-admin.steps.js
  specs/step_definitions/user-session-admin.steps.js
  src/data/input/types/blocked_file.doc
  src/data/input/types/safe_file.xlsx
  src/pages/dashboard.page.js
  src/utils/steps_file.js
Labels: Changes requested

#56 Added more feature and feature for policy history Feature-627
  content-management-policy-history.steps.js
  specs/features/content-management-policy-editing.feature
  specs/features/content-management-policy-history.feature
  specs/step_definitions/content-management-policy-editing.steps.js
  src/pages/policy.page.js
Labels: Changes requested

#59 Adding policy preview screen
  specs/features/content-management-previous-policy.feature
  specs/step_definitions/content-management-policy-history.steps.js
  specs/step_definitions/content-management-previous-policy.steps.js
  src/pages/policy.page.js
Labels: Changes requested

#60 request-history-filtering-by-risk-outcome & request-history-filtering-by-file-type steps
  specs/features/request-history-filtering-by-file-type.feature
  specs/features/request-history-filtering-by-risk-outcome.feature
  specs/step_definitions/request-history-filtering-by-file-type.steps.js
  specs/step_definitions/request-history-filtering-by-risk-outcome.steps.js
  src/pages/request-history.page.js
Labels: Changes requested
